version: '3.3'
services:
    api:
      build: .
      image: erwankerbrat/exemple_api_3
      ports:
        - "7481:5000" 
      environment:
        DATABASE_URL: "mysql://root:rootpassword@db:3306/db_test"
    db:
      image: erwankerbrat/copie_mysql
      volumes:
       - ./data-init:/docker-entrypoint-initdb.d  
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_test
          MYSQL_USER: username
          MYSQL_PASSWORD: password
